name: "linkcheck-action"
description: "Check links with filiph/linkcheck"
inputs:
  url: # id of input
    description: "The url or port of the site to check"
    required: true
  skip-file: # id of input
    description: "A file with routes to skip"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.url }}
    - --skip-file
    - ${{ inputs.skip-file }}
