name: "linkcheck-action"
description: "Check links with filiph/linkcheck"
inputs:
  arguments:
    description: 'The arguments you would pass to the linkcheck tool'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arguments }}
  entrypoint: 'sh -c /root/.pub-cache/bin/linkcheck $*'
