name: "linkcheck-action"
description: "Check links with filiph/linkcheck"
inputs:
  url:
    required: true
  skip-file:
    required: false
  check-external-links:
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
