name: "linkcheck-action"
description: "Check links with filiph/linkcheck"
inputs:
  arguments: # id of input
    description: "Pass the linkchek arguments"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: '["/root/.pub-cache/bin/linkcheck"]'
