name: "linkcheck-action"
description: "Check links with filiph/linkcheck"
inputs:
  url:
    required: true
  skipFile:
    required: false
  checkExternalLinks:
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
