name: Test linkcheck

on: push

linkcheck:
  runs-on: ubuntu-latest
  name: check links
  steps:
    - uses: actions/checkout@v2
    - name: Linkcheck
      id: linkcheck
      uses: ./
      with:
        arguments: https://wunderundfitzig.de -e --skip-file linkcheck-skip-file.txt
